""" ColorX_ui.py --

 UI generated by GUI Builder Build 146 on 2009-06-19 10:55:08 from:
    D:/10/dev/colorx/ColorX.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class ColorX(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._frame_1 = tkinter.Frame(root,
        )
        self._frame_2 = tkinter.Frame(root,
        )
        self._frame_3 = tkinter.Frame(root,
        )
        self._frame_4 = tkinter.Frame(root,
        )
        self._frame_5 = tkinter.Frame(root,
        )
        self._frame_6 = tkinter.Frame(root,
        )
        self._frame_15 = tkinter.Frame(root,
        )
        self._frame_16 = tkinter.Frame(root,
        )
        self._frame_17 = tkinter.Frame(root,
        )
        self._frame_18 = tkinter.Frame(root,
        )
        self._frame_21 = tkinter.Frame(root,
        )
        self._frame_22 = tkinter.Frame(root,
        )
        self._frame_23 = tkinter.Frame(root,
        )
        self._frame_25 = tkinter.Frame(root,
        )
        self._frame_26 = tkinter.Frame(root,
        )
        self._label_1 = tkinter.Label(root,
            activeforeground = "#ffffff",
            font = "Arial 10 bold",
            foreground = "#ffffff",
            text = "Color RGB-1",
        )
        self._label_2 = tkinter.Label(root,
            activeforeground = "#ffffff",
            font = "Arial 10 bold",
            foreground = "#ffffff",
            text = "Color RGB-2",
        )
        self._label_3 = tkinter.Label(root,
            activeforeground = "#ffffff",
            font = "Arial 10 bold",
            foreground = "#ffffff",
            text = "Color HSV-1",
        )
        self._label_4 = tkinter.Label(root,
            activeforeground = "#ffffff",
            font = "Arial 10 bold",
            foreground = "#ffffff",
            text = "Color HSV-2",
        )
        self._spinbox_1 = tkinter.Spinbox(self._frame_1,
            to = 255,
            width = 3,
        )
        self._spinbox_2 = tkinter.Spinbox(self._frame_1,
            to = 255,
            width = 3,
        )
        self._spinbox_3 = tkinter.Spinbox(self._frame_1,
            to = 255,
            width = 3,
        )
        self._button_1 = tkinter.Button(self._frame_15,
            text = "Convert to HSV-1",
        )
        self._spinbox_4 = tkinter.Spinbox(self._frame_2,
            to = 255,
            width = 3,
        )
        self._spinbox_5 = tkinter.Spinbox(self._frame_2,
            to = 255,
            width = 3,
        )
        self._spinbox_6 = tkinter.Spinbox(self._frame_2,
            to = 255,
            width = 3,
        )
        self._button_2 = tkinter.Button(self._frame_16,
            text = "Convert to HSV-2",
        )
        self._label_5 = tkinter.Label(root,
            activeforeground = "#ffffff",
            font = "Arial 10 bold",
            foreground = "#ffffff",
            text = "Mixed color RGB",
        )
        self._spinbox_7 = tkinter.Spinbox(self._frame_3,
            to = 359,
            width = 3,
        )
        self._spinbox_8 = tkinter.Spinbox(self._frame_3,
            to = 100,
            width = 3,
        )
        self._spinbox_9 = tkinter.Spinbox(self._frame_3,
            to = 100,
            width = 3,
        )
        self._button_3 = tkinter.Button(self._frame_17,
            text = "Convert  to RGB-1",
        )
        self._spinbox_10 = tkinter.Spinbox(self._frame_4,
            to = 359,
            width = 3,
        )
        self._spinbox_11 = tkinter.Spinbox(self._frame_4,
            to = 100,
            width = 3,
        )
        self._spinbox_12 = tkinter.Spinbox(self._frame_4,
            to = 100,
            width = 3,
        )
        self._button_4 = tkinter.Button(self._frame_18,
            text = "Convert to RGB-2",
        )
        self._label_6 = tkinter.Label(root,
            activeforeground = "#ffffff",
            font = "Arial 10 bold",
            foreground = "#ffffff",
            text = "Mixed color HSV",
        )
        self._label_7 = tkinter.Label(root,
            text = "Color RGB mix name",
        )
        self._label_8 = tkinter.Label(root,
            text = "Color HSV mix name",
        )
        self._label_9 = tkinter.Label(root,
            text = "Color RGB-1 name",
        )
        self._label_10 = tkinter.Label(root,
            text = "Color RGB-2 name",
        )
        self._label_11 = tkinter.Label(root,
            text = "Color HSV-1 name",
        )
        self._label_12 = tkinter.Label(root,
            text = "Color HSV-2 name",
        )
        self._spinbox_13 = tkinter.Spinbox(self._frame_5,
            state = "readonly",
            to = 255,
            width = 3,
        )
        self._spinbox_14 = tkinter.Spinbox(self._frame_5,
            state = "readonly",
            to = 255,
            width = 3,
        )
        self._spinbox_15 = tkinter.Spinbox(self._frame_5,
            state = "readonly",
            to = 255,
            width = 3,
        )
        self._button_5 = tkinter.Button(root,
            text = "Mix RGB colors",
        )
        self._spinbox_16 = tkinter.Spinbox(self._frame_6,
            state = "readonly",
            to = 360,
            width = 3,
        )
        self._spinbox_17 = tkinter.Spinbox(self._frame_6,
            state = "readonly",
            to = 100,
            width = 3,
        )
        self._spinbox_18 = tkinter.Spinbox(self._frame_6,
            state = "readonly",
            to = 100,
            width = 3,
        )
        self._button_6 = tkinter.Button(root,
            text = "Mix HSV colors",
        )
        self._label_13 = tkinter.Label(root,
            text = "Color CMYK-1 name",
        )
        self._label_14 = tkinter.Label(root,
            activeforeground = "#ffffff",
            font = "Arial 10 bold",
            foreground = "#ffffff",
            text = "Color CMYK-1",
        )
        self._label_15 = tkinter.Label(root,
            text = "Color CMYK-2 name",
        )
        self._label_16 = tkinter.Label(root,
            activeforeground = "#ffffff",
            font = "Arial 10 bold",
            foreground = "#ffffff",
            text = "Color CMYK-2",
        )
        self._spinbox_19 = tkinter.Spinbox(self._frame_21,
            to = 255,
            width = 3,
        )
        self._spinbox_20 = tkinter.Spinbox(self._frame_21,
            to = 255,
            width = 3,
        )
        self._spinbox_21 = tkinter.Spinbox(self._frame_21,
            to = 255,
            width = 3,
        )
        self._spinbox_23 = tkinter.Spinbox(self._frame_22,
            to = 255,
            width = 3,
        )
        self._spinbox_24 = tkinter.Spinbox(self._frame_22,
            to = 255,
            width = 3,
        )
        self._spinbox_25 = tkinter.Spinbox(self._frame_22,
            to = 255,
            width = 3,
        )
        self._spinbox_26 = tkinter.Spinbox(self._frame_22,
            to = 255,
            values = 255,
            width = 3,
        )
        self._spinbox_27 = tkinter.Spinbox(self._frame_23,
            state = "readonly",
            to = 255,
            width = 3,
        )
        self._spinbox_28 = tkinter.Spinbox(self._frame_23,
            state = "readonly",
            to = 255,
            width = 3,
        )
        self._spinbox_29 = tkinter.Spinbox(self._frame_23,
            state = "readonly",
            to = 255,
            width = 3,
        )
        self._spinbox_30 = tkinter.Spinbox(self._frame_23,
            state = "readonly",
            to = 255,
            values = 255,
            width = 3,
        )
        self._spinbox_22 = tkinter.Spinbox(self._frame_21,
            to = 255,
            values = 255,
            width = 3,
        )
        self._label_17 = tkinter.Label(root,
            text = "Color CMYK mix name",
        )
        self._label_18 = tkinter.Label(root,
            activeforeground = "#ffffff",
            font = "Arial 10 bold",
            foreground = "#ffffff",
            text = "Mixed color CMYK",
        )
        self._button_7 = tkinter.Button(root,
            text = "Mix CMYK colors",
        )
        self._button_9 = tkinter.Button(self._frame_15,
            text = "Convert to CMYK-1",
        )
        self._button_10 = tkinter.Button(self._frame_16,
            text = "Convert to CMYK-2",
        )
        self._button_11 = tkinter.Button(self._frame_17,
            text = "Convert to CMYK-1",
        )
        self._button_12 = tkinter.Button(self._frame_18,
            text = "Convert to CMYK-2",
        )
        self._button_13 = tkinter.Button(self._frame_25,
            text = "Convert to HSV-1",
        )
        self._button_14 = tkinter.Button(self._frame_25,
            text = "Convert to RGB-1",
        )
        self._button_15 = tkinter.Button(self._frame_26,
            text = "Convert to HSV-2",
        )
        self._button_16 = tkinter.Button(self._frame_26,
            text = "Convert to RGB-2",
        )

        # widget commands

        self._spinbox_1.configure(
            command = self._spinbox_1_command
        )
        self._spinbox_1.configure(
            invalidcommand = self._spinbox_1_invalidcommand
        )
        self._spinbox_1.configure(
            validatecommand = self._spinbox_1_validatecommand
        )
        self._spinbox_1.configure(
            xscrollcommand = self._spinbox_1_xscrollcommand
        )
        self._spinbox_2.configure(
            command = self._spinbox_2_command
        )
        self._spinbox_2.configure(
            invalidcommand = self._spinbox_2_invalidcommand
        )
        self._spinbox_2.configure(
            validatecommand = self._spinbox_2_validatecommand
        )
        self._spinbox_2.configure(
            xscrollcommand = self._spinbox_2_xscrollcommand
        )
        self._spinbox_3.configure(
            command = self._spinbox_3_command
        )
        self._spinbox_3.configure(
            invalidcommand = self._spinbox_3_invalidcommand
        )
        self._spinbox_3.configure(
            validatecommand = self._spinbox_3_validatecommand
        )
        self._spinbox_3.configure(
            xscrollcommand = self._spinbox_3_xscrollcommand
        )
        self._button_1.configure(
            command = self._button_1_command
        )
        self._spinbox_4.configure(
            command = self._spinbox_4_command
        )
        self._spinbox_4.configure(
            invalidcommand = self._spinbox_4_invalidcommand
        )
        self._spinbox_4.configure(
            validatecommand = self._spinbox_4_validatecommand
        )
        self._spinbox_4.configure(
            xscrollcommand = self._spinbox_4_xscrollcommand
        )
        self._spinbox_5.configure(
            command = self._spinbox_5_command
        )
        self._spinbox_5.configure(
            invalidcommand = self._spinbox_5_invalidcommand
        )
        self._spinbox_5.configure(
            validatecommand = self._spinbox_5_validatecommand
        )
        self._spinbox_5.configure(
            xscrollcommand = self._spinbox_5_xscrollcommand
        )
        self._spinbox_6.configure(
            command = self._spinbox_6_command
        )
        self._spinbox_6.configure(
            invalidcommand = self._spinbox_6_invalidcommand
        )
        self._spinbox_6.configure(
            validatecommand = self._spinbox_6_validatecommand
        )
        self._spinbox_6.configure(
            xscrollcommand = self._spinbox_6_xscrollcommand
        )
        self._button_2.configure(
            command = self._button_2_command
        )
        self._spinbox_7.configure(
            command = self._spinbox_7_command
        )
        self._spinbox_7.configure(
            invalidcommand = self._spinbox_7_invalidcommand
        )
        self._spinbox_7.configure(
            validatecommand = self._spinbox_7_validatecommand
        )
        self._spinbox_7.configure(
            xscrollcommand = self._spinbox_7_xscrollcommand
        )
        self._spinbox_8.configure(
            command = self._spinbox_8_command
        )
        self._spinbox_8.configure(
            invalidcommand = self._spinbox_8_invalidcommand
        )
        self._spinbox_8.configure(
            validatecommand = self._spinbox_8_validatecommand
        )
        self._spinbox_8.configure(
            xscrollcommand = self._spinbox_8_xscrollcommand
        )
        self._spinbox_9.configure(
            command = self._spinbox_9_command
        )
        self._spinbox_9.configure(
            invalidcommand = self._spinbox_9_invalidcommand
        )
        self._spinbox_9.configure(
            validatecommand = self._spinbox_9_validatecommand
        )
        self._spinbox_9.configure(
            xscrollcommand = self._spinbox_9_xscrollcommand
        )
        self._button_3.configure(
            command = self._button_3_command
        )
        self._spinbox_10.configure(
            command = self._spinbox_10_command
        )
        self._spinbox_10.configure(
            invalidcommand = self._spinbox_10_invalidcommand
        )
        self._spinbox_10.configure(
            validatecommand = self._spinbox_10_validatecommand
        )
        self._spinbox_10.configure(
            xscrollcommand = self._spinbox_10_xscrollcommand
        )
        self._spinbox_11.configure(
            command = self._spinbox_11_command
        )
        self._spinbox_11.configure(
            invalidcommand = self._spinbox_11_invalidcommand
        )
        self._spinbox_11.configure(
            validatecommand = self._spinbox_11_validatecommand
        )
        self._spinbox_11.configure(
            xscrollcommand = self._spinbox_11_xscrollcommand
        )
        self._spinbox_12.configure(
            command = self._spinbox_12_command
        )
        self._spinbox_12.configure(
            invalidcommand = self._spinbox_12_invalidcommand
        )
        self._spinbox_12.configure(
            validatecommand = self._spinbox_12_validatecommand
        )
        self._spinbox_12.configure(
            xscrollcommand = self._spinbox_12_xscrollcommand
        )
        self._button_4.configure(
            command = self._button_4_command
        )
        self._spinbox_13.configure(
            command = self._spinbox_13_command
        )
        self._spinbox_13.configure(
            invalidcommand = self._spinbox_13_invalidcommand
        )
        self._spinbox_13.configure(
            validatecommand = self._spinbox_13_validatecommand
        )
        self._spinbox_13.configure(
            xscrollcommand = self._spinbox_13_xscrollcommand
        )
        self._spinbox_14.configure(
            command = self._spinbox_14_command
        )
        self._spinbox_14.configure(
            invalidcommand = self._spinbox_14_invalidcommand
        )
        self._spinbox_14.configure(
            validatecommand = self._spinbox_14_validatecommand
        )
        self._spinbox_14.configure(
            xscrollcommand = self._spinbox_14_xscrollcommand
        )
        self._spinbox_15.configure(
            command = self._spinbox_15_command
        )
        self._spinbox_15.configure(
            invalidcommand = self._spinbox_15_invalidcommand
        )
        self._spinbox_15.configure(
            validatecommand = self._spinbox_15_validatecommand
        )
        self._spinbox_15.configure(
            xscrollcommand = self._spinbox_15_xscrollcommand
        )
        self._button_5.configure(
            command = self._button_5_command
        )
        self._spinbox_16.configure(
            command = self._spinbox_16_command
        )
        self._spinbox_16.configure(
            invalidcommand = self._spinbox_16_invalidcommand
        )
        self._spinbox_16.configure(
            validatecommand = self._spinbox_16_validatecommand
        )
        self._spinbox_16.configure(
            xscrollcommand = self._spinbox_16_xscrollcommand
        )
        self._spinbox_17.configure(
            command = self._spinbox_17_command
        )
        self._spinbox_17.configure(
            invalidcommand = self._spinbox_17_invalidcommand
        )
        self._spinbox_17.configure(
            validatecommand = self._spinbox_17_validatecommand
        )
        self._spinbox_17.configure(
            xscrollcommand = self._spinbox_17_xscrollcommand
        )
        self._spinbox_18.configure(
            command = self._spinbox_18_command
        )
        self._spinbox_18.configure(
            invalidcommand = self._spinbox_18_invalidcommand
        )
        self._spinbox_18.configure(
            validatecommand = self._spinbox_18_validatecommand
        )
        self._spinbox_18.configure(
            xscrollcommand = self._spinbox_18_xscrollcommand
        )
        self._button_6.configure(
            command = self._button_6_command
        )
        self._spinbox_19.configure(
            command = self._spinbox_19_command
        )
        self._spinbox_19.configure(
            invalidcommand = self._spinbox_19_invalidcommand
        )
        self._spinbox_19.configure(
            validatecommand = self._spinbox_19_validatecommand
        )
        self._spinbox_19.configure(
            xscrollcommand = self._spinbox_19_xscrollcommand
        )
        self._spinbox_20.configure(
            command = self._spinbox_20_command
        )
        self._spinbox_20.configure(
            invalidcommand = self._spinbox_20_invalidcommand
        )
        self._spinbox_20.configure(
            validatecommand = self._spinbox_20_validatecommand
        )
        self._spinbox_20.configure(
            xscrollcommand = self._spinbox_20_xscrollcommand
        )
        self._spinbox_21.configure(
            command = self._spinbox_21_command
        )
        self._spinbox_21.configure(
            invalidcommand = self._spinbox_21_invalidcommand
        )
        self._spinbox_21.configure(
            validatecommand = self._spinbox_21_validatecommand
        )
        self._spinbox_21.configure(
            xscrollcommand = self._spinbox_21_xscrollcommand
        )
        self._spinbox_23.configure(
            command = self._spinbox_23_command
        )
        self._spinbox_23.configure(
            invalidcommand = self._spinbox_23_invalidcommand
        )
        self._spinbox_23.configure(
            validatecommand = self._spinbox_23_validatecommand
        )
        self._spinbox_23.configure(
            xscrollcommand = self._spinbox_23_xscrollcommand
        )
        self._spinbox_24.configure(
            command = self._spinbox_24_command
        )
        self._spinbox_24.configure(
            invalidcommand = self._spinbox_24_invalidcommand
        )
        self._spinbox_24.configure(
            validatecommand = self._spinbox_24_validatecommand
        )
        self._spinbox_24.configure(
            xscrollcommand = self._spinbox_24_xscrollcommand
        )
        self._spinbox_25.configure(
            command = self._spinbox_25_command
        )
        self._spinbox_25.configure(
            invalidcommand = self._spinbox_25_invalidcommand
        )
        self._spinbox_25.configure(
            validatecommand = self._spinbox_25_validatecommand
        )
        self._spinbox_25.configure(
            xscrollcommand = self._spinbox_25_xscrollcommand
        )
        self._spinbox_26.configure(
            command = self._spinbox_26_command
        )
        self._spinbox_26.configure(
            invalidcommand = self._spinbox_26_invalidcommand
        )
        self._spinbox_26.configure(
            validatecommand = self._spinbox_26_validatecommand
        )
        self._spinbox_26.configure(
            xscrollcommand = self._spinbox_26_xscrollcommand
        )
        self._spinbox_27.configure(
            command = self._spinbox_27_command
        )
        self._spinbox_27.configure(
            invalidcommand = self._spinbox_27_invalidcommand
        )
        self._spinbox_27.configure(
            validatecommand = self._spinbox_27_validatecommand
        )
        self._spinbox_27.configure(
            xscrollcommand = self._spinbox_27_xscrollcommand
        )
        self._spinbox_28.configure(
            command = self._spinbox_28_command
        )
        self._spinbox_28.configure(
            invalidcommand = self._spinbox_28_invalidcommand
        )
        self._spinbox_28.configure(
            validatecommand = self._spinbox_28_validatecommand
        )
        self._spinbox_28.configure(
            xscrollcommand = self._spinbox_28_xscrollcommand
        )
        self._spinbox_29.configure(
            command = self._spinbox_29_command
        )
        self._spinbox_29.configure(
            invalidcommand = self._spinbox_29_invalidcommand
        )
        self._spinbox_29.configure(
            validatecommand = self._spinbox_29_validatecommand
        )
        self._spinbox_29.configure(
            xscrollcommand = self._spinbox_29_xscrollcommand
        )
        self._spinbox_30.configure(
            command = self._spinbox_30_command
        )
        self._spinbox_30.configure(
            invalidcommand = self._spinbox_30_invalidcommand
        )
        self._spinbox_30.configure(
            validatecommand = self._spinbox_30_validatecommand
        )
        self._spinbox_30.configure(
            xscrollcommand = self._spinbox_30_xscrollcommand
        )
        self._spinbox_22.configure(
            command = self._spinbox_22_command
        )
        self._spinbox_22.configure(
            invalidcommand = self._spinbox_22_invalidcommand
        )
        self._spinbox_22.configure(
            validatecommand = self._spinbox_22_validatecommand
        )
        self._spinbox_22.configure(
            xscrollcommand = self._spinbox_22_xscrollcommand
        )
        self._button_7.configure(
            command = self._button_7_command
        )
        self._button_9.configure(
            command = self._button_9_command
        )
        self._button_10.configure(
            command = self._button_10_command
        )
        self._button_11.configure(
            command = self._button_11_command
        )
        self._button_12.configure(
            command = self._button_12_command
        )
        self._button_13.configure(
            command = self._button_13_command
        )
        self._button_14.configure(
            command = self._button_14_command
        )
        self._button_15.configure(
            command = self._button_15_command
        )
        self._button_16.configure(
            command = self._button_16_command
        )


        # Geometry Management
        self._frame_1.grid(
            in_    = root,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_2.grid(
            in_    = root,
            column = 3,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_3.grid(
            in_    = root,
            column = 3,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_4.grid(
            in_    = root,
            column = 3,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_5.grid(
            in_    = root,
            column = 3,
            row    = 7,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_6.grid(
            in_    = root,
            column = 3,
            row    = 8,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_15.grid(
            in_    = root,
            column = 4,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_16.grid(
            in_    = root,
            column = 4,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_17.grid(
            in_    = root,
            column = 4,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_18.grid(
            in_    = root,
            column = 4,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_21.grid(
            in_    = root,
            column = 3,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_22.grid(
            in_    = root,
            column = 3,
            row    = 6,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_23.grid(
            in_    = root,
            column = 3,
            row    = 9,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_25.grid(
            in_    = root,
            column = 4,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._frame_26.grid(
            in_    = root,
            column = 4,
            row    = 6,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._label_1.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._label_2.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._label_3.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._label_4.grid(
            in_    = root,
            column = 1,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._spinbox_1.grid(
            in_    = self._frame_1,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_2.grid(
            in_    = self._frame_1,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_3.grid(
            in_    = self._frame_1,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_1.grid(
            in_    = self._frame_15,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._spinbox_4.grid(
            in_    = self._frame_2,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_5.grid(
            in_    = self._frame_2,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_6.grid(
            in_    = self._frame_2,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_2.grid(
            in_    = self._frame_16,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._label_5.grid(
            in_    = root,
            column = 1,
            row    = 7,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._spinbox_7.grid(
            in_    = self._frame_3,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_8.grid(
            in_    = self._frame_3,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_9.grid(
            in_    = self._frame_3,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_3.grid(
            in_    = self._frame_17,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._spinbox_10.grid(
            in_    = self._frame_4,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_11.grid(
            in_    = self._frame_4,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_12.grid(
            in_    = self._frame_4,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_4.grid(
            in_    = self._frame_18,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._label_6.grid(
            in_    = root,
            column = 1,
            row    = 8,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._label_7.grid(
            in_    = root,
            column = 2,
            row    = 7,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "new"
        )
        self._label_8.grid(
            in_    = root,
            column = 2,
            row    = 8,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "new"
        )
        self._label_9.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "new"
        )
        self._label_10.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "new"
        )
        self._label_11.grid(
            in_    = root,
            column = 2,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "new"
        )
        self._label_12.grid(
            in_    = root,
            column = 2,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "new"
        )
        self._spinbox_13.grid(
            in_    = self._frame_5,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_14.grid(
            in_    = self._frame_5,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_15.grid(
            in_    = self._frame_5,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_5.grid(
            in_    = root,
            column = 4,
            row    = 7,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._spinbox_16.grid(
            in_    = self._frame_6,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_17.grid(
            in_    = self._frame_6,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_18.grid(
            in_    = self._frame_6,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_6.grid(
            in_    = root,
            column = 4,
            row    = 8,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._label_13.grid(
            in_    = root,
            column = 2,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "new"
        )
        self._label_14.grid(
            in_    = root,
            column = 1,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._label_15.grid(
            in_    = root,
            column = 2,
            row    = 6,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "new"
        )
        self._label_16.grid(
            in_    = root,
            column = 1,
            row    = 6,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._spinbox_19.grid(
            in_    = self._frame_21,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_20.grid(
            in_    = self._frame_21,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_21.grid(
            in_    = self._frame_21,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_23.grid(
            in_    = self._frame_22,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_24.grid(
            in_    = self._frame_22,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_25.grid(
            in_    = self._frame_22,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_26.grid(
            in_    = self._frame_22,
            column = 4,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_27.grid(
            in_    = self._frame_23,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_28.grid(
            in_    = self._frame_23,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_29.grid(
            in_    = self._frame_23,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_30.grid(
            in_    = self._frame_23,
            column = 4,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_22.grid(
            in_    = self._frame_21,
            column = 4,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_17.grid(
            in_    = root,
            column = 2,
            row    = 9,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "new"
        )
        self._label_18.grid(
            in_    = root,
            column = 1,
            row    = 9,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._button_7.grid(
            in_    = root,
            column = 4,
            row    = 9,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "n"
        )
        self._button_9.grid(
            in_    = self._frame_15,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ne"
        )
        self._button_10.grid(
            in_    = self._frame_16,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ne"
        )
        self._button_11.grid(
            in_    = self._frame_17,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ne"
        )
        self._button_12.grid(
            in_    = self._frame_18,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ne"
        )
        self._button_13.grid(
            in_    = self._frame_25,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ne"
        )
        self._button_14.grid(
            in_    = self._frame_25,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._button_15.grid(
            in_    = self._frame_26,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ne"
        )
        self._button_16.grid(
            in_    = self._frame_26,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 36, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 41, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 51, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 41, pad = 0)
        root.grid_rowconfigure(5, weight = 0, minsize = 41, pad = 0)
        root.grid_rowconfigure(6, weight = 0, minsize = 46, pad = 0)
        root.grid_rowconfigure(7, weight = 0, minsize = 39, pad = 0)
        root.grid_rowconfigure(8, weight = 0, minsize = 34, pad = 0)
        root.grid_rowconfigure(9, weight = 0, minsize = 35, pad = 0)
        root.grid_columnconfigure(1, weight = 1, minsize = 2, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 61, pad = 0)
        root.grid_columnconfigure(3, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(4, weight = 0, minsize = 2, pad = 0)
        self._frame_1.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_1.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_1.grid_columnconfigure(2, weight = 0, minsize = 2, pad = 0)
        self._frame_1.grid_columnconfigure(3, weight = 0, minsize = 51, pad = 0)
        self._frame_15.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_15.grid_columnconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_15.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_16.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_16.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_16.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_17.grid_rowconfigure(1, weight = 0, minsize = 19, pad = 0)
        self._frame_17.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_17.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_18.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_18.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_18.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_2.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_2.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_2.grid_columnconfigure(2, weight = 0, minsize = 2, pad = 0)
        self._frame_2.grid_columnconfigure(3, weight = 0, minsize = 50, pad = 0)
        self._frame_21.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_21.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_21.grid_columnconfigure(2, weight = 0, minsize = 35, pad = 0)
        self._frame_21.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._frame_21.grid_columnconfigure(4, weight = 0, minsize = 40, pad = 0)
        self._frame_22.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_22.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_22.grid_columnconfigure(2, weight = 0, minsize = 39, pad = 0)
        self._frame_22.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._frame_22.grid_columnconfigure(4, weight = 0, minsize = 40, pad = 0)
        self._frame_23.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_23.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_23.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_23.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._frame_23.grid_columnconfigure(4, weight = 0, minsize = 40, pad = 0)
        self._frame_25.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_25.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_25.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)
        self._frame_26.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_26.grid_columnconfigure(1, weight = 0, minsize = 88, pad = 0)
        self._frame_26.grid_columnconfigure(2, weight = 0, minsize = 9, pad = 0)
        self._frame_3.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_3.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_3.grid_columnconfigure(2, weight = 0, minsize = 2, pad = 0)
        self._frame_3.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._frame_4.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_4.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_4.grid_columnconfigure(2, weight = 0, minsize = 11, pad = 0)
        self._frame_4.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_5.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_5.grid_columnconfigure(2, weight = 0, minsize = 30, pad = 0)
        self._frame_5.grid_columnconfigure(3, weight = 0, minsize = 42, pad = 0)
        self._frame_6.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_6.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_6.grid_columnconfigure(2, weight = 0, minsize = 16, pad = 0)
        self._frame_6.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)


