""" ColorX.py --

 UI generated by GUI Builder Build 146 on 2009-06-19 10:56:04 from:
    D:/10/dev/colorx/ColorX.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""


from tkinter import *
from ColorX import CustomColorX


def quit(self, *args):
    pass


def main():
    # try: 
    #     userinit()
    # except NameError: 
    #     pass
    root = Tk()
    demo = CustomColorX(root)
    root.title('ColorX')
    # try: 
    #     run()
    # except NameError: 
    #     pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': 
    main()
